apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyhewnvf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tyhewnvf
  template:
    metadata:
      labels:
        app: tyhewnvf
    spec:
      containers:
      - image: okteto.dev/tyhewnvf:latest
        name: tyhewnvf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "7ddfdeb8-1e80-4024-bfc6-b89ed32e4b27"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "7ddfdeb8-1e80-4024-bfc6-b89ed32e4b27"
        - name: Vmess_Path
          value: "/vm666hygtt5r"
        - name: Share_Path
          value: "/djfusyt87"
